-- SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT 
-- SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULT
-- SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION 
CREATE DATABASE IF NOT EXISTS hbtn_0c_0;
